config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :kittens

  # Defines the root path route ("/")
  # root "articles#index"
  root "kittens#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/kitten.rb
class Kitten < ApplicationRecord
    validates :name, presence: true
    validates :age, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController
    def index
        @kittens = Kitten.all

        respond_to do |format|
            format.html
            format.json { render :json => @kittens }
        end
    end
    
    def show
        @kitten = Kitten.find(params[:id])
        
        respond_to do |format|
            format.html
            format.json { render :json => @kitten }
        end
    end

    def new
        @kitten = Kitten.new
    end

    def create
        @kitten = Kitten.new(kitten_params())

        if @kitten.save
            redirect_to @kitten, notice: "Kitten successfully created!"
        else
            render :new, status: :unprocessable_entity
        end
    end

    def edit
        @kitten = Kitten.find(params[:id])
    end

    def update
        @kitten = Kitten.find(params[:id])

        if @kitten.update(kitten_params())
            redirect_to @kitten, notice: "Kitten successfully updated!"
        else
            render :edit, status: :unprocessable_entity
        end
    end

    def destroy
        @kitten = Kitten.find(params[:id])
        @kitten.destroy

        redirect_to root_path, status: :see_other, notice: "Kitten successfully deleted!"
    end


    private
    def kitten_params
        params.require(:kitten).permit(:name, :age, :cuteness, :softness)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/_form.html.erb
<div style="color: red">
    <% @kitten.errors.each do |error| %>
        <%= error.full_message %><br>
    <% end %>
</div>

<%= form_with model: @kitten do |form| %>
    <div>
        <%= form.label :name %>
        <%= form.text_field :name %>
    </div>
    
    <div>
        <%= form.label :age %>
        <%= form.number_field :age %>
    </div>
    
    <div>
        <%= form.label :cuteness %>
        <%= form.range_field :cuteness, min: 1, max: 10 %>
    </div>
    <div>
        <%= form.label :softness %>
        <%= form.range_field :softness, min: 1, max: 10 %>
    </div>

    <div>
        <%= form.submit "Submit" %>
    </div>
<% end %>

app/views/kittens/edit.html.erb
<h1>Edit Kitten</h1>

<%= render "form" %>

<%= link_to "Remove Kitten", kitten_path(@kitten), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>

app/views/kittens/index.html.erb
<% flash.each do |type, message| %>
    <%= message %>
<% end %>

<h1>Kittens</h1>

<p><%= link_to "Add Kitten", new_kitten_path %></p>

<% @kittens.each do |kitten| %>
    <div>
        <%= link_to kitten.name, kitten_path(kitten) %><br>
        <%= link_to "Remove Kitten", kitten_path(kitten), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
    </div><br>
<% end %>

app/views/kittens/new.html.erb
<h1>Add Kitten</h1>

<%= render "form" %>

app/views/kittens/show.html.erb
<% flash.each do |type, message| %>
    <%= message %>
<% end %>

<h1><%= @kitten.name %></h1>

<p>Age: <%= @kitten.age %></p>
<p>Cuteness: <%= @kitten.cuteness %></p>
<p>Softness: <%= @kitten.softness %></p>

<%= link_to "Edit Kitten", edit_kitten_path(@kitten) %><br>
<%= link_to "Remove Kitten", kitten_path(@kitten), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %><br>
<%= link_to "Back to kittens", root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinKittens</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>